### ISSUE TITLE
running errors MetGEMs

### ISSUE THREAD

**Issue by fauzul2017** [yumyai/MetGEMs#2]
After successfull installation of MetGEMs, running codes gives following errors. What will be the potential solutions.

metgem markp -i feature-table.tsv -t taxonomy_gg.tsv -m k_core -o output_ko.tsv
Traceback (most recent call last):
  File "/home/X/anaconda3/envs/metgem_env/bin/metgem", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/X/MetGEM/scripts/metgem", line 39, in <module>
    retCode = main()
  File "/home/X/MetGEM/scripts/metgem", line 32, in main
    taskmodule.run()
  File "/home/X/MetGEM/metgem/tasks/markp.py", line 50, in run
    modeltab = model.map2model(asvdata)
  File "/home/ngc2/MetGEM/metgem/model.py", line 101, in map2model
    log.info("Genus match to model {} - {}".format(gnuse))
IndexError: tuple index out of range

**Comment by yumyai** [comment]
Hi fauzul2017,

Thank you very much for the report. I already pushed the fix into the master branch. This new commit should have no problem there. 

Best,
Preecha

**Comment by fauzul2017** [comment]
Thanks
Congratulations for developing this interesting method.

Best Regards
Fauzul Mobeen
