### ISSUE TITLE
Silva Database; ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by MonicaSteffi** [yumyai/MetGEMs#4]
Dear Author,
Sorry for the basic question. I did my taxonomic classification using silva database in DADA2 and tried to execute MetGem. But contionusly Iam getting the following error.
```
Traceback (most recent call last):
  File "/home/monica/.local/bin/metgem", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "MetGEMs-master/MetGEM/scripts/metgem", line 39, in <module>
    retCode = main()
  File "MetGEMs-master/MetGEM/scripts/metgem", line 32, in main
    taskmodule.run()
  File MetGEMs-master/MetGEM/metgem/tasks/markp.py", line 53, in run
    taxtab = read_taxatable(args.taxtsv)
  File "MetGEMs-master/MetGEM/metgem/utils.py", line 103, in read_taxatable
    taxondf = pd.DataFrame.from_records(predf.Taxon.apply(gg_parse)).reindex(
  File "/home/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4138, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "/MetGEMs-master/MetGEM/metgem/utils.py", line 191, in gg_parse
    abbrv, taxa = token.split("__")
ValueError: too many values to unpack (expected 2)
```

Kindly check the attached file. Every row has equal number of "__" and ";". 
https://docs.google.com/spreadsheets/d/1dAIB3Do7IpHJmJ3ui4AN6NIziI2VZjFz8EQf4NceEp0/edit?usp=sharing

Any help would be appreciated

**Comment by mruehlemann** [comment]
Hi! I think all you need to do is include a space after each of the ";" as the delimiter for splitting is defined as "; "
